# Generated by Django 2.0.6 on 2018-06-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BinanceExchangeInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('minQty', models.CharField(max_length=20)),
                ('maxQty', models.CharField(max_length=20)),
                ('stepSize', models.CharField(max_length=20)),
            ],
        ),
    ]
