# Generated by Django 2.0.6 on 2018-06-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BinanceExchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='binanceexchangeinformation',
            name='baseAsset',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='binanceexchangeinformation',
            name='maxPrice',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='binanceexchangeinformation',
            name='minPrice',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='binanceexchangeinformation',
            name='quoteAsset',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='binanceexchangeinformation',
            name='tickSize',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
